User.create!(name: 'Jan Kowalsky',
			 email: 'jan@kowalsky.com',
			 password: 'SSecurity',
			 password_confirmation: 'SSecurity',
			 address: 'Andersa 7',
			 city: 'Poznań',
			 postal_code: '61-111',
			 phone: '777 998 779',
			 activated: true,
			 activated_at: Time.zone.now)